apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persisent-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
